name: Android CI CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Set up SDK
      uses: android-actions/setup-android@v2

    - name: Access MAPS_API_KEY
      env:
        APOD_API_KEY: ${{ secrets.MAPS_API_KEY }}
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clean Bulid
      run: ./gradlew clean build

    - name: Run Android Test
      uses: reactivecircus/android-emulator-runner@v2
      with:
       api-level: 24
       target: default
       arch: x86
       profile: Nexus 6
       script: ./gradlew connectedCheck --stacktrace
       run: ./gradlew connectedAndroidTest

    - name: Sign APK
      id: sign
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEY_STORE_JKS_BASE64 }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"

    - name: Build Release APK
      run: |
          ./gradlew :app:assembleRelease

    - name: Upload Release Build to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-artifacts
        path: app/build/outputs/apk/release/
        if-no-files-found: error

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
       name: debug
       path: ./app/build/outputs/apk/debug/app-debug.apk