name: Android CI

on:
  push:
    branches: [ "main" ]
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Set up SDK
      uses: android-actions/setup-android@v2

    - name: Access MAPS_API_KEY
      env:
        APOD_API_KEY: ${{ secrets.MAPS_API_KEY }}
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clean Bulid
      run: ./gradlew clean build
        
    - name: Run Android Test
      uses: reactivecircus/android-emulator-runner@v2
      with:
       api-level: 24
       target: default
       arch: x86
       profile: Nexus 6
       script: ./gradlew connectedCheck --stacktrace
       run: ./gradlew connectedAndroidTest
