name: Android CI CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Access MAPS_API_KEY
      env:
        APOD_API_KEY: ${{ secrets.MAPS_API_KEY }}
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clean Bulid
      run: ./gradlew clean build
        
    - name: Set up SDK
      uses: android-actions/setup-android@v2

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
       name: debug
       path: ./app/build/outputs/apk/debug/app-debug.apk
