name: Android CD

on: 
  workflow_dispatch
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Set up SDK
      uses: android-actions/setup-android@v2

    - name: Access MAPS_API_KEY
      env:
        APOD_API_KEY: ${{ secrets.MAPS_API_KEY }}
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Bulid
      run: ./gradlew build

    - name: Sign APK
      id: sign
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEY_STORE_JKS_BASE64 }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"

    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: app/build/outputs/apk/release/app-release-unsigned-signed.apk
        if-no-files-found: error

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
       name: debug
       path: ./app/build/outputs/apk/debug/app-debug.apk